services:
  - type: web
    name: profittown-2
    runtime: node
    plan: starter
    autoDeploy: true
    buildCommand: bun install && bun run build
    startCommand: bun migrate && node dist/src/index.js
    envVars:
      - fromGroup: profittown-2/bot
      - key: TZ
        value: Africa/Lagos
      - key: DATABASE_URL
        fromDatabase:
          name: profittown-2
          property: connectionString
databases:
  - name: profittown-2
    user: admin
    plan: basic-256mb
